# Generated by Django 2.1.2 on 2018-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, default=0)),
                ('name', models.CharField(max_length=40)),
                ('game1', models.IntegerField(blank=True, default=0)),
                ('game2', models.IntegerField(blank=True, default=0)),
                ('total', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
